app/views/view.py
import os

from datetime import datetime
from flask import Blueprint, render_template, redirect, url_for, flash, request
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from flask_socketio import send

from app import db, images, socketio
from app.models import User, Role, Chat
from app.forms import SignUpForm, SignInForm, EditProfileForm, ChatForm


app_blueprint = Blueprint("app", __name__)


@app_blueprint.route('/', methods=['GET'])
def home():
    return render_template("home.html")


@app_blueprint.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    userid = User.query.filter_by(id=current_user.id).first()
    name = current_user.name
    regtime = current_user.regtime
    image_file = url_for('static', filename=f'images/profile_pics/{userid.image_file}')

    if not os.path.exists(f"app/{image_file}"):
        userid.image_file = "default.png"
        image_file = url_for('static', filename=f'images/profile_pics/default.png')
    
    return render_template('profile.html', name=name, image_file=image_file, regtime=regtime, userid=userid)

    
@app_blueprint.route("/profile/update_profile", methods=["GET", "POST"])
def edit_profile():
    form = EditProfileForm()
    userid = User.query.filter_by(id=current_user.id).first()
    chat_record = Chat.query.filter_by(user_id=current_user.id).first()
    name = current_user.name
    regtime = current_user.regtime
    image_file = url_for('static', filename=f'images/profile_pics/{userid.image_file}')

    if not os.path.exists(f"app/{image_file}"):
        userid.image_file = "default.png"
        image_file = url_for('static', filename=f'images/profile_pics/default.png')

    if form.validate_on_submit():
        try:
            file_full_name = str(form.pic.data).split()[1].replace("'", "")
            ext = file_full_name.split(".")[1]

            if userid.image_file == "default.png":
                images.save(storage=form.pic.data, name=f"{userid.id}.{ext}")
            else:
                if os.remove(f"{userid.id}.{ext}"):
                    images.save(storage=form.pic.data, name=f"{userid.id}.{ext}")
            
            userid.image_file = f"{userid.id}.{ext}"
            db.session.commit()
            
        except:
            pass

        if form.name.data != None and len(form.name.data) != 0:
            if form.name.data != userid.name:
                userid.name = form.name.data
                db.session.commit()

                chat_record.username = form.name.data
                db.session.commit()
                return redirect(url_for('app.profile'))

            flash("This name is already taken!", "error")

        return redirect(url_for('app.profile'))

    return render_template("edit_profile.html", name=name, image_file=image_file, regtime=regtime, userid=userid, form=form)


@app_blueprint.route("/profile/delete", methods=["GET", "POST"])
def delete_profile():
    user = User.query.filter_by(id=current_user.id).first()
    user_role = Role.query.filter_by(id=current_user.id).first()

    if user and user_role:
        db.session.delete(user)
        db.session.commit()

        db.session.delete(user_role)
        db.session.commit()
    
    else:
        return redirect(url_for("app.home"))
    
    return redirect(url_for("app.home"))


@app_blueprint.route("/signup", methods=['GET', "POST"])
def signup():
    form = SignUpForm()

    if form.validate_on_submit():
        login = form.login.data
        name = form.name.data
        password = form.password.data
        regtime = datetime.strftime(datetime.now(), "%d/%m/%Y %H:%M:%S")

        user = User.query.filter_by(login=login).first()
        user_name = User.query.filter_by(name=name).first()

        if not user and not user_name and len(password) > 8:
            new_user = User(
                login=login,
                name=name,
                password=generate_password_hash(password, method='sha256'),
                regtime=regtime
            )

            simple_user_role = Role(name='user')
            new_user.roles = [simple_user_role,]

            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('app.signin'))

        flash('The fields are filled in incorrectly', 'error')

    return render_template("signup.html", form=form)


@app_blueprint.route("/signin", methods=['GET', "POST"])
def signin():
    form = SignInForm()

    if form.validate_on_submit():
        login = form.login.data
        password = form.password.data
        remember = form.remember.data

        user = User.query.filter_by(login=login).first()

        if user and check_password_hash(user.password, password):
            login_user(user, remember=remember)
            return redirect(request.args.get("next") or url_for('app.profile'))
        
        flash("Password or login entered incorrectly!", "error")

    return render_template("signin.html", form=form)


@app_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('app.home'))


@socketio.on("message")
def message_handler(message):
    profile = User.query.filter_by(id=current_user.id).first()
    date = datetime.strftime(datetime.now(), "%d-%B %H:%M")

    if message != "User connected!":
        if Chat.query.filter_by(id=Chat.id).count() == 50:
            db.session.query(Chat).delete()
        
        name = profile.name
        new_message = Chat(
            message=message.split(";")[0], 
            username=name, 
            user_id=profile.id, 
            date=date, 
            user_pic=profile.image_file
        )

        db.session.add(new_message)
        db.session.commit()

        send(message, broadcast=True)


@app_blueprint.route("/chat", methods=["GET"])
@login_required
def chat():
    form = ChatForm()
    data = Chat.query.order_by(Chat.id.asc()).all()
    profile = User.query.filter_by(id=current_user.id).first()
    return render_template("chat.html", form=form, data=data, profile=profile)


@app_blueprint.route("/check_profile/<user_name>", methods=["GET", "POST"])
@login_required
def check_profile(user_name):
    profile = User.query.filter_by(name=user_name).first()
    image_file = url_for('static', filename=f'images/profile_pics/{profile.image_file}')
    return render_template("check_profile.html", profile=profile, image_file=image_file)

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="{{ url_for('static', filename='images/site-icon.png') }}" type="image/jpg">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" 
    integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" 
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.5.3/socket.io.js" 
    integrity="sha512-iWPnCISAd/J+ZacwV2mbNLCaPGRrRo5OS81lKTVPtRg1wGTC20Cfmp5Us5RcbLv42QLdbAWl0MI57yox5VecQg==" 
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

app/templates/chat.html
{% extends 'base.html' %}

{% block title %}
Online Chat
{% endblock %}

{% block body %}

<div class="home-nav-panel">
    <a href="{{ url_for('app.home') }}" class="home-nav-panel-elements">Home</a>
</div>

<div class="chat">
    <div id="messages">
        {% for el in data %}
            {% if el.user_id == current_user.id %}
                <div id="my">
                    <h6 id="date-my">
                        {{ el.date }}
                    </h6>

                    <h4 id="myMessage">
                        {{ el.message }}
                    </h4>
                </div>
            {% else %}
                <div id="other">
                    <h4 id="name-other">
                        {{ el.username }}
                        <h6 id="date-other">
                            {{ el.date }}
                        </h6>
                    </h4>

                    <a href="{{ url_for('app.check_profile', user_name=el.username) }}">
                        <img src="static/images/profile_pics/{{ el.user_pic}}" id="other-chat-pic">
                    </a>

                    <h4 id="otherMessage">
                        {{ el.message }}
                    </h4>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

<script>
    $(document).ready(function() {
        const monthNames = ["January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"
        ];
        var socket = io();
        const d = new Date();

        socket.on('connect', function() {
            socket.send("User connected!");
        });

        socket.on('message', function(data) {
            if (data.split(";")[1] == "{{ current_user.id }}") {
                $("#messages").append(
                    $('<h6>').text(
                        d.getDate() + "-" + 
                        monthNames[d.getMonth()] + " " + 
                        d.getHours() + ":" + 
                        d.getMinutes()
                        ).attr("id", "date-my"),

                    $('<h4>').text(data.split(";")[0]).attr("id", "myMessage")
                );
            }
            else {
                $("#messages").append(
                    $('<h4>').text(data.split(";")[2]).attr("id", "name-other"),

                    $('<h6>').text(
                        d.getDate() + "-" + 
                        monthNames[d.getMonth()] + " " + 
                        d.getHours() + ":" + 
                        d.getMinutes()
                        ).attr("id", "date-other"),

                    $("<a>").attr("href", "/check_profile/" + data.split(";")[2]).append(
                    $("<img>").attr("src", "static/images/profile_pics/" + data.split(";")[3])
                    .attr("id", "other-chat-pic")
                    ),

                    $('<h4>').text(data.split(";")[0]).attr("id", "otherMessage")
                );
            };
            
            $('.chat').scrollTop($('.chat')[0].scrollHeight);
        });

        $("#send_message").on('click', function() {
            if ($('#message').val() != "") {
                socket.send(
                    $('#message').val() + ";" + 
                    "{{ current_user.id }}" + ";" + 
                    "{{ current_user.name }}" + ";" +
                    "{{ current_user.image_file }}"
                );

                $('#message').val("");
                $('.chat').scrollTop($('.chat')[0].scrollHeight);
            };
        });
    });
</script>

<div class="chat-form">
    {{ form.message(id="message", autocomplete='off') }}
    {{ form.send(id="send_message") }}
</div>

{% endblock %}

app/templates/check_profile.html
{% extends 'base.html' %}

{% block title %}
Check Profile
{% endblock %}

{% block body %}

<div class="flash">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, message in messages %}
          <b><div class="{{ category }}">{{message}}</div></b>
        {% endfor %}
    {% endwith %}
</div>

<div class="home-nav-panel">
    <a href="{{ url_for('app.chat') }}" class="home-nav-panel-elements">Back</a>
</div>

<div class="profile">
    <h2 class="profile-h2">{{ profile.name }}'s Profile</h2>

    <div class="profile-text">
        <div class="profile-block">
            <span class="profile-span">Registered: {{ profile.regtime }}</span>
            <span class="profile-span">Username: {{ profile.name }}</span>
        </div>
    </div>

    <img src="{{ image_file }}" class="profile-pic" id="check-profile-pic">
</div>

{% endblock %}

app/templates/edit_profile.html
{% extends 'base.html' %}

{% block title %}
Edit Profile
{% endblock %}

{% block body %}

<div class="flash">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, message in messages %}
          <b><div class="{{ category }}">{{message}}</div></b>
        {% endfor %}
    {% endwith %}
</div>

<div class="home-nav-panel">
    <a class="home-nav-panel-elements" onclick="window.location.replace('/profile')">Cancel</a>
</div>

<div class="profile">
    <h2 class="edit-profile-h2">Edit Your Profile</h2>

    <img src="{{ image_file }}" id="profile-pic">

    <div class="profile-text">
        <form method="POST" action="{{ url_for('app.edit_profile') }}" enctype="multipart/form-data">
            <div class="edit-profile-block">
                <span class="profile-span">Registered: {{ regtime }}</span>
                <span>Username: {{ form.name(class='edit-name-field', autocomplete='off') }}</span>
                
                {{ form.submit(class="edit-profile", id="submit-edit-profile") }}

                <a href="/profile/delete" class="edit-profile e" id="delete-acc-btn">Delete Account</a>

                <label for="edit-pic-btn" id="edit-pic-label">Edit Pic</label>
                {{ form.pic(id='edit-pic-btn') }}
            </div>
        </form>
    </div>

</div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block title %}
Online Chat 🇺🇦
{% endblock %}

{% block body %}
<div class="home-logo">
    <h1 class="home-logo-elements">
        Online Chat
        <img src="static/images/ukraine-sign.png" style="width: 1.8%;">
    </h1>
    <p class="home-logo-elements">Speak without limits with different people from all Ukraine!</p>
</div>

<div class="home-nav-panel">
    {% if not current_user.is_authenticated %}
    <a href="{{ url_for('app.signin') }}" class="home-nav-panel-elements">Sign in</a>
    <a href="{{ url_for('app.signup') }}" class="home-nav-panel-elements">Sign up</a>
    {% else %}
    <a href="{{ url_for('app.logout') }}" class="home-nav-panel-elements">Logout</a>
    <a href="{{ url_for('app.profile') }}" class="home-nav-panel-elements">My Profile</a>
    {% endif %}
</div>


{% if current_user.is_authenticated %}
    <div class="wrap">
        <a href="{{ url_for('app.chat') }}" class="home-nav-panel-elements chat-nav">Start Chating!</a>
    </div>
{% endif %}



{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}

{% block title %}
My Profile
{% endblock %}

{% block body %}

<div class="flash">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, message in messages %}
          <b><div class="{{ category }}">{{message}}</div></b>
        {% endfor %}
    {% endwith %}
</div>

<div class="home-nav-panel">
    <a href="{{ url_for('app.home') }}" class="home-nav-panel-elements">Home</a>
    <a href="{{ url_for('app.logout') }}" class="home-nav-panel-elements">Logout</a>    
</div>

<div class="profile">
    <h2 class="profile-h2">Your Profile</h2>

    <div class="profile-text">
        <div class="profile-block">
            <span class="profile-span">Registered: {{ regtime }}</span>
            <span class="profile-span">Username: {{ name }}</span>
            <a href="/profile/update_profile" class="edit-profile-redirect profile-span">Edit Profile</a>
        </div>
    </div>

    <img src="{{ image_file }}" class="profile-pic">
</div>

{% endblock %}

app/templates/signin.html
{% extends 'base.html' %}

{% block title %}
Sign in
{% endblock %}

{% block body %}

<div class="flash">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, message in messages %}
          <b><div class="{{ category }}">{{message}}</div></b>
        {% endfor %}
    {% endwith %}
</div>


<div class="form">
    <form method="POST" action="">
        {{ form.login(class='form-element field', autocomplete='off') }}<br>
        {{ form.password(class='form-element field', autocomplete='off') }}<br>
        {{ form.sign_in(class='form-element signin home-nav-panel-elements') }}

        <span class='form-element' id="remain">
            remain me {{ form.remember(class='form-element') }}
        </span>
    </form>
</div>



{% endblock %}

app/templates/signup.html
{% extends 'base.html' %}

{% block title  %}
Sign up
{% endblock %}

{% block body  %}

<div class="flash">
  {% with messages = get_flashed_messages(with_categories=true) %}
      {% for category, message in messages %}
        <b><div class="{{ category }}">{{message}}</div></b>
      {% endfor %}
  {% endwith %}
</div>

<div class="form">
  <form method="POST" action="/signup">
      {{ form.login(class='form-element field', autocomplete='off') }}<br>
      {{ form.name(class='form-element field', autocomplete='off') }}<br>
      {{ form.password(class='form-element field', autocomplete='off') }}<br>
      {{ form.sign_up(class='form-element signup home-nav-panel-elements') }}
  </form>
</div>

{% endblock %}